= Course Setup for 510G Android

This directory tries to automate the setup as much as possible.

== TO CONFIGURE A STUDENT MACHINE

* In a PowerShell AS ADMIN window,  download the setpaths file:

	Start-BitsTransfer -Destination SetPaths.ps1 -Source https://raw.githubusercontent.com/IanDarwin/510G-CourseLoad/main/SetPaths.ps1

* If the student logs in with a name other than 'student', edit the new file _Setup1.bat_ 
and change globally, case-insensitively from _student_ to their name.

* In the same window, allow running unsigned P/S scripts:

	set-executionpolicy Unrestricted

	You must accept the resulting prompt in the affirmative!

* In the same window, run the script to set paths

	cd ~
	.\SetPaths.ps1
	Note: this must be run or parts of the main script will fail

* Start a NEW CMD window (must be new to get the PATH changes!), download the main setup script

	cd %USERPROFILE%
	curl -O https://raw.githubusercontent.com/IanDarwin/510G-CourseLoad/main/Setup1.bat 

* If the student logs in with a name other than 'student', edit the new file _Setup1.bat_ 
and change globally, case-insensitively from _student_ to their name.

* Unless you are sure that Git Bash (MinGW) is installed:

	winget install --id Git.Git -e

* Run the main script:

	.\Setup1.bat

* Watch for errors. After the first one, you can come back when it's done. 
Remember to complete the "manual steps" shown at the end of the output.

== Structure

I have configured this for the following overall setup - these will be added
to each student's directory:

* CourseFiles510G - exercises, solutions, samples
* Downloads/... - downloads for installing programs for later chapters
	so the students can learn to set these up
* Pictures/ - one image file used in a do-now
* bin - a few shell scripts/batch files
* lib - a few Java Jar files etc.
* javasrc - extra Java samples that we might refer to in response to questions
* AndroidCookbookExamples - extra Android examples that might be used

== Assumptions

We presume that:

* The students log in as "student" on these machines
* The student machines have Windows 10/11
* The student machines have "winget" installed (it was optional on some early Win10).
* The student machines have the git-bash (MinGW) package installed and on PATH
* The student machines have recent Python 3 installed standardly (so that "pip install" will work).

The Setup1.bat file is a command script using:

* WinGet to install java, intellij idea, android studio, etc
* git to install CourseFiles510G, javasrc, Android-Cookbook-Examples
* curl to download a few files
* tar to extract bin, lib, Downloads, Maven

== Manual Steps

The following did not get automated. Please:

* Set the home directory in whatever browser the students are using, to 

	file://Users/Student/CourseFiles510G/website/index.html

== Summary

The Setup1 script will stitch together all the files needed for the course.

== Future Work

There should be a way to keep the versions in sync, between what's installed
by setup1 and what's added to path. The "Merge" described below would make
this much easier.

It should be possible to do all of this with one script. It cannot be a .bat file because
command.com sets a lenght of 1024 on PATH, which is way too little. 
I wrestled with this for some hours, but am not a powershell expert and
was not able to complete it. If somebody wants to try, clone the repo
and checkout the merge-bat-and-ps branch, then pull all the changes into
the two split files before manually fixing the merged script, and running
it a couple of times to be sure it works. Good for someone with time on their hands.
