= Course Setup for 510G Android

This directory tries to automate the setup as much as possible.
The scripting here hopes to stitch together all the files needed for the course.

Note that some bits and pieces of Android Studio - like the Emulators and platform APIs - 
cannot be downloaded automatically and must be downloaded by running Android Studio. We get the students to do this
as part of an early exercise.

== TO CONFIGURE A STUDENT MACHINE

=== Assumptions

We presume that:

* The student machines have Windows 10/11
* The student machines have "winget" installed (it was optional on some early Win10).
* The student machines have the git-bash (MinGW) package installed and on PATH
* The student machines have recent Python *3* installed standardly (so that "pip install" will work).
Note that this is not used or tested by the script but will be needed; I omitted it from the setup script
on the grounds that LT student machines always seem to have Python installed.

=== Steps

There are two scripts that must be downloaded. The directions below assume you didn't download a Zip of the 510G-CourseLoad project.
If you did, you can of course skip the two "download" steps.

. Right click on _PowerShell_ and do _Run As Administrator_. 

. In this Admin Powershell window,  download the setpaths file:

	Start-BitsTransfer -Destination SetPaths.ps1 -Source https://raw.githubusercontent.com/IanDarwin/510G-CourseLoad/main/SetPaths.ps1

. In the powershell admin window, allow running unsigned P/S scripts:

	set-executionpolicy Unrestricted

You must accept the resulting prompt in the affirmative!

. In the same powershell window, run the script to set paths

	cd ~
	.\SetPaths.ps1

Note: If you get prompted with "Security Warning: Run only scripts that you trust...", respond with "R" for Run.

Note: this script must run, and succeed with only yellow or white outputs, no reds, else parts of the main script will probably fail

. We need some of the tools that are downloaded by the script to be usable while the script is running.
And they are only made available by the PATH changes in SetPaths.
Therefore you *must* start a *new* "Command Prompt" window at this point (Not even a new tab within WinTerm;
must be a whole new process to get the PATH changes we just made!). 
This window does not need admin privs.

. *Switch to this new window for all the following steps!*

. In the new "command prompt" window, download the main setup script:

	cd %USERPROFILE%
	curl -O https://raw.githubusercontent.com/IanDarwin/510G-CourseLoad/main/Setup1.bat 

. Unless you are sure that Git Bash (MinGW) is installed:

	winget install --id Git.Git 

. Run the main script. This will take at least 15 minutes, maybe 30.

	.\Setup1.bat

. Watch for errors. Errors installing or building anything are probably bad news.
However, issues during the long and chatty JavaScript stage towards the end do not matter.

. VERIFY: Please check in the new window, that:

.. emulator is on PATH (_where emulator_ or _which emulator_ should give a long path with Android SDK)
.. _java -version_ reports 17.x, not 11.x
.. project folders got created, e.g., in CourseFiles510G/sourcecode, there are pairs
of folders, like _ex32solution_ and _ex32_, _ex21solution_ and _ex21_, etc.
(the _exXX_ are genned from the _exXXsolution_ during the setup script;
a few solutions won't have exercise folders but if the majority do, we're good).

=== Manual Steps

The following did not get automated, sorry. Please do the following after the scripts run:

. Set the home directory in whatever browser the students are using, to 

	file:///C:/Users/student/CourseFiles510G/website/index.html

After the first machine completes OK, on subsequent machines you can come back when it's done. 
It took about 15-30 minutes on a fast, lightly-loaded network when developing the script.
Please remember to complete the "manual steps" shown at the end of the output.

== Structure

I have configured this for the following overall setup - these will be added
to each student's directory:

* CourseFiles510G - exercises, solutions, samples
* Downloads/... - downloads for installing programs for later chapters
	so the students can learn to set these up
* Pictures/ - one image file used in a do-now
* bin - a few shell scripts/batch files
* lib - a few Java Jar files etc.
* javasrc - extra Java samples that we might refer to in response to questions
* AndroidCookbookExamples - extra Android examples that might be used

The Setup1.bat file is a command script using:

* WinGet to install java, intellij idea, android studio, etc
* git to install CourseFiles510G, javasrc, Android-Cookbook-Examples
* curl to download a few files
* tar to extract bin, lib, Downloads, Maven

== Future Work

There is never going to be a Setup2.bat file, so we could rename the main file to setup.

The source code should be built using Chris Mawata's build system, and all the JavaScript
"errors"/warnings dealt with.

A few of the packages that we install annoyingly include the full version number, like _15.0.1.2-Stable-This-Week_,
into the PATH, and we have to set those PATHs manually (this is part of the work in _SetPaths.ps1_).
There should be a way to keep the version numbers in sync as we upgrade this over time, between what's installed
by setup1 and what's added to path. The "Merge" described below would make
this much easier.

It should be possible to do all of this with one script. It cannot be a .bat file because
command.com sets a lenght of 1024 on PATH, which is way too little. 
I wrestled with this merger attempt for some hours, but am not a powershell expert and
was not able to complete it. If somebody wants to try, clone the repo
and checkout the merge-bat-and-ps branch, then pull all the changes into
the two split files before manually fixing the merged script, and running
it a couple of times to be sure it works. Good for someone with time on their hands.
