= Course Setup for 510G Android

This directory tries to automate the setup as much as possible.
The scripting here hopes to stitch together all the files needed for the course.

Note that some bits and pieces of Android Studio - like the Emulators and platform APIs - 
cannot be downloaded automatically and must be downloaded by running Android Studio. We get the students to do this
as part of an early exercise.


== TO CONFIGURE A STUDENT MACHINE

* Right click on _PowerShell_ and do _Run As Administrator_. In this window,  download the setpaths file:

	Start-BitsTransfer -Destination SetPaths.ps1 -Source https://raw.githubusercontent.com/IanDarwin/510G-CourseLoad/main/SetPaths.ps1

* If the student logs in with a name other than 'student', edit the new file _SetPaths.ps1_
and change globally, case-insensitively from _student_ to their name.

* In the same window, allow running unsigned P/S scripts:

	set-executionpolicy Unrestricted

	You must accept the resulting prompt in the affirmative!

* In the same window, run the script to set paths

	cd ~
	.\SetPaths.ps1
	Note: this must be run or parts of the main script will fail

* We need some of the tools that are downloaded to be usable during the script.
Thus you *must* start a *new* CMD window (Not even a new tab within WinTerm;
must be a whole new process to get the PATH changes we just made!). 
In this new window, download the main setup script:

	cd %USERPROFILE%
	curl -O https://raw.githubusercontent.com/IanDarwin/510G-CourseLoad/main/Setup1.bat 

* If the student logs in with a name other than 'student', edit the new file _Setup1.bat_ 
and change globally, case-insensitively from _student_ to their name.

* Unless you are sure that Git Bash (MinGW) is installed:

	winget install --id Git.Git 

* Run the main script:

	.\Setup1.bat

* Watch for errors. After the first machine completes OK, on subsequent machines you can come back when it's done. 
It took about 15 minutes on a fast, lightly-loaded network when developing the script.
Remember to complete the "manual steps" shown at the end of the output.

== Structure

I have configured this for the following overall setup - these will be added
to each student's directory:

* CourseFiles510G - exercises, solutions, samples
* Downloads/... - downloads for installing programs for later chapters
	so the students can learn to set these up
* Pictures/ - one image file used in a do-now
* bin - a few shell scripts/batch files
* lib - a few Java Jar files etc.
* javasrc - extra Java samples that we might refer to in response to questions
* AndroidCookbookExamples - extra Android examples that might be used

== Assumptions

We presume that:

* The students log in as "student" on these machines
* The student machines have Windows 10/11
* The student machines have "winget" installed (it was optional on some early Win10).
* The student machines have the git-bash (MinGW) package installed and on PATH
* The student machines have recent Python 3 installed standardly (so that "pip install" will work).

The Setup1.bat file is a command script using:

* WinGet to install java, intellij idea, android studio, etc
* git to install CourseFiles510G, javasrc, Android-Cookbook-Examples
* curl to download a few files
* tar to extract bin, lib, Downloads, Maven

== Manual Steps

The following did not get automated, sorry. Please:

* Set the home directory in whatever browser the students are using, to 

	file:///C:/Users/student/CourseFiles510G/website/index.html


== Future Work

There is never going to be a Setup2.bat file, so we could rename the main file to setup.

A few of the package installed annoyingly include the full version number, like _15.0.1.2-Stable-This-Week_,
into the PATH, and we have to set those PATHs manually (hence, part of the work in _SetPaths.ps1_).
There should be a way to keep the versions in sync, between what's installed
by setup1 and what's added to path. The "Merge" described below would make
this much easier.

It should be possible to do all of this with one script. It cannot be a .bat file because
command.com sets a lenght of 1024 on PATH, which is way too little. 
I wrestled with this for some hours, but am not a powershell expert and
was not able to complete it. If somebody wants to try, clone the repo
and checkout the merge-bat-and-ps branch, then pull all the changes into
the two split files before manually fixing the merged script, and running
it a couple of times to be sure it works. Good for someone with time on their hands.
